apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx       # Deployment label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx      # Deployment selector matches the Pod label
  template:
    metadata:
      labels:
        app: nginx    # Pod label
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

