apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx         # Service selector matches the Deployment label
  ports:
  - port: 80           # Service Port
    targetPort: 8080   # targetPort matches the Container Port
